# Generated by Django 5.2.4 on 2025-07-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electronics", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"verbose_name": "Контакт", "verbose_name_plural": "Контакты"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Продукт", "verbose_name_plural": "Продукты"},
        ),
        migrations.RemoveField(
            model_name="electronicsnetwork",
            name="contacts",
        ),
        migrations.RemoveField(
            model_name="electronicsnetwork",
            name="products",
        ),
        migrations.AddField(
            model_name="electronicsnetwork",
            name="contacts",
            field=models.ManyToManyField(to="electronics.contact", verbose_name="Контакты"),
        ),
        migrations.AddField(
            model_name="electronicsnetwork",
            name="products",
            field=models.ManyToManyField(to="electronics.product", verbose_name="Продукты"),
        ),
    ]
